require 'rspotify/connection'
require 'rspotify/version'

module RSpotify
  autoload :Album,                'rspotify/album'
  autoload :Artist,               'rspotify/artist'
  autoload :AudioFeatures,        'rspotify/audio_features'
  autoload :AudioAnalysis,        'rspotify/audio_analysis'
  autoload :AudioAnalysisBar,     'rspotify/audio_analysis_bar'
  autoload :AudioAnalysisBeat,    'rspotify/audio_analysis_beat'
  autoload :AudioAnalysisMeta,    'rspotify/audio_analysis_meta'
  autoload :AudioAnalysisSection, 'rspotify/audio_analysis_section'
  autoload :AudioAnalysisSegment, 'rspotify/audio_analysis_segment'
  autoload :AudioAnalysisTrack,   'rspotify/audio_analysis_track'
  autoload :AudioAnalysisTatum,   'rspotify/audio_analysis_tatum'
  autoload :Base,                 'rspotify/base'
  autoload :Category,             'rspotify/category'
  autoload :Device,               'rspotify/device'
  autoload :Episode,              'rspotify/episode'
  autoload :Player,               'rspotify/player'
  autoload :Playlist,             'rspotify/playlist'
  autoload :Recommendations,      'rspotify/recommendations'
  autoload :RecommendationSeed,   'rspotify/recommendation_seed'
  autoload :Show,                 'rspotify/show'
  autoload :Track,                'rspotify/track'
  autoload :TrackLink,            'rspotify/track_link'
  autoload :User,                 'rspotify/user'
end
